### ISSUE TITLE
Clarify confidential-survey use case

### ISSUE THREAD

**Issue by pburkholder** [18F/compliance-toolkit#27]
The README.md references https://github.com/18F/cg-application-ssp-example, which in turn has the file, https://github.com/18F/cg-application-ssp-example/blob/master/ExampleApplicationComponent/component.yaml, which reads:

```
documentation_complete: false
name: Application Component Example
verifications:
  hakiri:
    name: Hakiri Results
    path: https://hakiri.io/github/18F/confidential-survey/develop
    type: URL
  gemnasium:
    name: Gemnasium Results
    path: https://gemnasium.com/18F/confidential-survey
    type: URL
  code_climate:
    name: Code Climate Results
    path: https://codeclimate.com/github/18F/confidential-survey
    type: URL
satisfies:
  NIST-800-53:
    SA-11 (1):
      narrative: |
        Code Climate is a code analysis tool that combines the results of multiple static analysis tools. The Confidential Survey application uses the Hakiri and Gemnasium engines in Code Climate to verify that the code is secure and has no outdated dependencies.
      references:
      - verification: code_climate
      - verification: gemnasium
      - verification: hakiri
```

However, the actual confidential-survey application, https://github.com/18F/confidential-survey, doesn't have the above code or anything seemingly related to opencontrol other than https://github.com/18F/confidential-survey/blob/develop/system-security-plan.yml

Which leads to a couple of questions:
- Does the snippet above come from any real, working application or is it an example of goal to someday implement?
- Does the system-security-plan.yml in confidential-survey play into this compliance framework?

Thanks, Peter
